## «*El mundo exige resultados. No cuentes a otros tus dolores del parto. Muéstrales al niño.*»

### [Indira Gandhi](https://es.wikipedia.org/wiki/Indira_Gandhi)

# SI03 Pandas

Actividad individual.

Utilice el dataset asignado en [datasets panda](https://docs.google.com/spreadsheets/d/e/2PACX-1vQi3ziCNg_TlAHPvHceFDyqFZeouQk7-uWcSSv-VTsYHnzx5VEyp3u_rp5pNiuPdNta898xj7vJzZPL/pubhtml).

Resuelva los siguientes ejercicios con códigos que se ajusten al PEP8. Recuerde incluir los comentarios en el código y documentar las funciones con docstrings al estilo de Google.

**Importante:**

**no se permite la utilización de ciclos (for or while) para resolver los ejercicios.**

**todos los ejercicios deben ser resueltos con Pandas.**

# Preparación del ejercicio

*   Importe las librerías requeridas
*   Lea el dataset a utilizar desde una url

**Sugerencia**: suba el dataset a un repositorio de GitHub, o al Googledrive de su **cuenta personal de gmail** y luego publíquelo en la web como un archivo *.csv.

Nota: si lo desea puede utilizar otro método para obtener la url del dataset.

In [5]:
try:
    # Importar las librerías necesarias
    import urllib.request
    import csv
    import pandas as pd
    from colorama import init, Fore, Style

    # Inicializar Colorama con autoreset=True
    init(autoreset=True)

    # Ejemplo de uso de negrita
    print(Fore.RED + Style.BRIGHT + "Este texto será rojo y en negrita.")
    print("Este texto será el color predeterminado y en negrita.")


    
    # Conocer la versiones de las librerías instaladas
    print("Versión de urllib.request:", urllib.request.__version__)
    print("Versión de csv:", csv.__version__)
    print("Versión de pandas:", pd.__version__)

    # Guardar en la variable 'ruta' la url del dataset
    ruta = ("https://raw.githubusercontent.com/BluessyJazz/"
            "Programacion-Para-Ingenieria_2024-1/main/SI03%20Pandas/"
            "2023_rankings.csv")

    # Cargar el dataset a partir de la ruta establecida
    urllib.request.urlretrieve(ruta, "2023_rankings.csv")

    # Verificar la lectura del dataset
    # Cargar el archivo CSV en un DataFrame
    df = pd.read_csv("2023_rankings.csv")

    # Mostrar las primeras filas del DataFrame para verificar la lectura
    print(df.head())

    # Ruta donde se encuentra alojado el archivo
    datos = "2023_rankings.csv"

except urllib.error.URLError as e:
    print("Error al acceder a la URL:", e)

except FileNotFoundError:
    print("No se encontró el archivo CSV.")

except pd.errors.EmptyDataError:
    print("El archivo CSV está vacío.")

except pd.errors.ParserError:
    print("Error al leer el archivo CSV.")

except Exception as e:
    print("Se produjo un error inesperado:", e)

Versión de urllib.request: 3.12
Versión de csv: 1.0
Versión de pandas: 2.2.1

   rank_order   rank        \
0           10  1
1           20  2
2           30  =3
3           40  =3
4           50  5

  name                                                                                                 \
0  University of Oxford                          ...
1  Harvard University                            ...
2  University of Cambridge                       ...
3  Stanford University                           ...
4  Massachusetts Institute of Technology         ...

   scores_overall   scores_overall_rank   scores_teaching   \
0  96.4                               10  92.3
1  95.2                               20  94.8
2  94.8                               30  90.9
3  94.8                               40  94.2
4  94.2                               50  90.7

   scores_teaching_rank   scores_research   scores_research_rank   \
0                      5  99.7                                  1
1                      1  99.0                                  3
2                      7  99.5                                  2
3                      2  96.7                                  7
4                      8  93.6                                 11

   scores_citations   ...  scores_international_outlook_rank   \
0  99.0               ...                                  28
1  99.3               ...                                 214
2  97.0               ...                                  34
3  99.8               ...                                 223
4  99.8               ...                                 119

   location               stats_number_students   stats_student_staff_ratio   \
0  United Kingdom           20,965                                     10.6
1  United States            21,887                                      9.6
2  United Kingdom           20,185                                     11.3
3  United States            16,164                                      7.1
4  United States            11,415                                      8.2

   stats_pc_intl_students   stats_female_male_ratio   \
0  42%                      48 : 52
1  25%                      50 : 50
2  39%                      47 : 53
3  24%                      46 : 54
4  33%                      40 : 60

  aliases                                                                                                                        \
0  University of Oxford                          ...
1  Harvard University                            ...
2  University of Cambridge                       ...
3  Stanford University                           ...
4  Massachusetts Institute of Technology         ...

  subjects_offered                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
0  Accounting & Finance,General Engineering,Commu...
1  Mathematics & Statistics,Civil Engineering,Lan...
2  Business & Management,General Engineering,Art,...
3  Physics & Astronomy,Computer Science,Politics ...
4  Mathematics & Statistics,Languages, Literature...

   closed  unaccredited
0  False          False
1  False          False
2  False          False
3  False          False
4  False          False

[5 rows x 24 columns]

## Ejercicio 00

Muestre las principales características del dataset utilizando pandas.

En particular muestre los nombres de las columnas y sus tipos; el índice del dataset; la forma del dataset.

In [ ]:
"""
Resuelva los siguientes ejercicios con códigos que se ajusten al PEP8. Recuerde incluir los comentarios en el código y documentar las funciones con docstrings al estilo de Google.

**Importante:**

**no se permite la utilización de ciclos (for or while) para resolver los ejercicios.**

**todos los ejercicios deben ser resueltos con Pandas.**

Muestre las principales características del dataset utilizando pandas.

En particular muestre los nombres de las columnas y sus tipos; el índice del dataset; la forma del dataset.
"""

# Mostrar los nombres de las columnas y sus tipos
print("\nNombres de las columnas y sus tipos:")

## Ejercicio 01

Cree el df_01 con las siguientes características:

Diez columnas (dentro de las diez columnas deben estar la primera y la última columna del dataset original).

Diez filas (las filas deben corresponder a las cinco primeras filas y las cinco últimas filas del dataset original).

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí

## Ejercicio 02

Modifique el índice del df_01 creado en el paso anterior.

Opción 1: utilice una de las columnas de df_01 como el nuevo índice.

Opción 2: cree el índice a partir de una secuencia cronológica.

Cambie los nombres de las columnas del DataFrame a "Primera", "segunda", etcétera.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí

## Ejercicio 03

Utilizando el método **loc** seleccione los elementos que se encuentran entre la tercera y la sexta fila y en las columnas cuarta, quinta y octava de DataFrame modificado.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí

## Ejercicio 04

Utilizando el método **iloc** seleccione los elementos que se encuentran entre la tercera y la sexta fila y en las columnas cuarta, quinta y octava del DataFrame modificado.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí

## Ejercicio 05

Calcule el promedio de una de las columnas numéricas del DataFrame modificado.

Cree el DataFrame df_02 conservando todas las columnas del DataFrame modificado y seleccionando los valores superiores al promedio en la columna numérica que tomó como referencia para el ejercicio.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí

## Ejercicio 06

Seleccione una columna del DataFrame **original** que contenga una variable categórica (si no hay variables categóricas cree una columna con variables categóricas a partir de alguna columna numérica del DataFrame).

Utilice el método **groupby** para analizar la información del DataFrame a partir de la variable categórica seleccionada.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí

## Ejercicio 07

Cree una tabla dinámica, utilizando el método **pivottable**, para analizar la información del DataFrame **original**.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí

## Ejercicio 08

Encuentre todos los valores nulos del DataFrame original y cambie esos valores nulos con la media de la respectiva columna.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí

## Ejercicio 09

Encuentre todos los valores nulos del DataFrame original y elimine la fila correspondiente.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Escriba su código aquí